import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/organisms/header";
// import styles from "../styles/Home.module.css";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
      </main>
    </div>
  );
};

export default Home;
