import Head from "next/head";
import { FunctionComponent } from "react";
import Header from "../organisms/header";
import styles from "./Layout.module.scss";

interface PublicLayoutProps {
  children: JSX.Element | JSX.Element[];
}

const PublicLayout: FunctionComponent<PublicLayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Prothom alo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-white relative">
        <Header />
        <main className={styles?.content_wrapper}>{children}</main>
      </div>
    </>
  );
};

export default PublicLayout;
